[build]
  base = "/"
  command = "yarn build"
  publish = "packages/site/dist"
  functions = "packages/api/handlers"

[build.environment]
  PLATFORM = "netlify"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/check/*"
  to = "/check/index.html"
  status = 200

[[plugins]]
  package = "netlify-plugin-chromium"
  [plugins.inputs]
    packageManager = "yarn"

[[headers]]
  for = "/*"
  [headers.values]
